# Generated by Django 4.2.30 on 2026-06-01 20:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HarakatBaholash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=100, verbose_name='Ism')),
                ('familiya', models.CharField(max_length=100, verbose_name='Familiya')),
                ('yosh', models.PositiveIntegerField(verbose_name='Yosh')),
                ('harakat_turi', models.CharField(choices=[('yugurish', 'Yugurish'), ('yurish', 'Yurish'), ('suzish', 'Suzish'), ('velosiped', 'Velosiped minish'), ('gimnastika', 'Gimnastika'), ('boshqa', 'Boshqa')], max_length=50, verbose_name='Harakat turi')),
                ('daraja', models.CharField(choices=[('boshlangich', "Boshlang'ich"), ('orta', "O'rta"), ('yuqori', 'Yuqori'), ('professional', 'Professional')], max_length=50, verbose_name='Daraja')),
                ('davomiylik_daqiqa', models.FloatField(verbose_name='Davomiylik (daqiqa)')),
                ('masofа_km', models.FloatField(default=0, verbose_name='Masofa (km)')),
                ('yurak_urishi', models.PositiveIntegerField(default=0, verbose_name='Yurak urishi (urib/min)')),
                ('izoh', models.TextField(blank=True, verbose_name='Izoh')),
                ('ai_tahlil', models.TextField(blank=True, verbose_name='AI Tahlili')),
                ('baho', models.FloatField(blank=True, null=True, verbose_name='Umumiy baho (0-100)')),
                ('sana', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Sana')),
            ],
            options={
                'verbose_name': 'Harakat baholash',
                'verbose_name_plural': 'Harakat baholashlar',
                'ordering': ['-sana'],
            },
        ),
        migrations.CreateModel(
            name='StatistikaMa_lumot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kalit', models.CharField(max_length=100, unique=True)),
                ('qiymat', models.JSONField()),
                ('yangilangan', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Statistika',
            },
        ),
    ]
